# Loanstatus-b

In [2]:
import numpy as np 
import pandas as pd

In [3]:
dataset = pd.read_csv(r"C:\Users\DELL\Downloads\Loanstatus.csv")

In [4]:
dataset

Loan_ID  Gender Married Dependents     Education Self_Employed  \
0    LP001002    Male      No          0      Graduate            No   
1    LP001003    Male     Yes          1      Graduate            No   
2    LP001005    Male     Yes          0      Graduate           Yes   
3    LP001006    Male     Yes          0  Not Graduate            No   
4    LP001008    Male      No          0      Graduate            No   
5    LP001011    Male     Yes          2      Graduate           Yes   
6    LP001013    Male     Yes          0  Not Graduate            No   
7    LP001014    Male     Yes         3+      Graduate            No   
8    LP001018    Male     Yes          2      Graduate            No   
9    LP001020    Male     Yes          1      Graduate            No   
10   LP001024    Male     Yes          2      Graduate            No   
11   LP001027    Male     Yes          2      Graduate           NaN   
12   LP001028    Male     Yes          2      Graduate            No   
13   LP001029    Male      No          0      Graduate            No   
14   LP001030    Male     Yes          2      Graduate            No   
15   LP001032    Male      No          0      Graduate            No   
16   LP001034    Male      No          1  Not Graduate            No   
17   LP001036  Female      No          0      Graduate            No   
18   LP001038    Male     Yes          0  Not Graduate            No   
19   LP001041    Male     Yes          0      Graduate           NaN   
20   LP001043    Male     Yes          0  Not Graduate            No   
21   LP001046    Male     Yes          1      Graduate            No   
22   LP001047    Male     Yes          0  Not Graduate            No   
23   LP001050     NaN     Yes          2  Not Graduate            No   
24   LP001052    Male     Yes          1      Graduate           NaN   
25   LP001066    Male     Yes          0      Graduate           Yes   
26   LP001068    Male     Yes          0      Graduate            No   
27   LP001073    Male     Yes          2  Not Graduate            No   
28   LP001086    Male      No          0  Not Graduate            No   
29   LP001087  Female      No          2      Graduate           NaN   
..        ...     ...     ...        ...           ...           ...   
584  LP002911    Male     Yes          1      Graduate            No   
585  LP002912    Male     Yes          1      Graduate            No   
586  LP002916    Male     Yes          0      Graduate            No   
587  LP002917  Female      No          0  Not Graduate            No   
588  LP002925     NaN      No          0      Graduate            No   
589  LP002926    Male     Yes          2      Graduate           Yes   
590  LP002928    Male     Yes          0      Graduate            No   
591  LP002931    Male     Yes          2      Graduate           Yes   
592  LP002933     NaN      No         3+      Graduate           Yes   
593  LP002936    Male     Yes          0      Graduate            No   
594  LP002938    Male     Yes          0      Graduate           Yes   
595  LP002940    Male      No          0  Not Graduate            No   
596  LP002941    Male     Yes          2  Not Graduate           Yes   
597  LP002943    Male      No        NaN      Graduate            No   
598  LP002945    Male     Yes          0      Graduate           Yes   
599  LP002948    Male     Yes          2      Graduate            No   
600  LP002949  Female      No         3+      Graduate           NaN   
601  LP002950    Male     Yes          0  Not Graduate           NaN   
602  LP002953    Male     Yes         3+      Graduate            No   
603  LP002958    Male      No          0      Graduate            No   
604  LP002959  Female     Yes          1      Graduate            No   
605  LP002960    Male     Yes          0  Not Graduate            No   
606  LP002961    Male     Yes          1      Graduate            No   
607  LP002964    Male     Yes          2  Not 

In [6]:
dataset.isnull().any()

Loan_ID              False
Gender                True
Married               True
Dependents            True
Education            False
Self_Employed         True
ApplicantIncome      False
CoapplicantIncome    False
LoanAmount            True
Loan_Amount_Term      True
Credit_History        True
Property_Area        False
Loan_Status          False
dtype: bool

In [10]:
dataset = dataset.replace(to_replace = "3+")

In [11]:
dataset["Dependents"].unique()

array(['0', '1', '2', nan], dtype=object)

In [12]:
dataset

Loan_ID  Gender Married Dependents     Education Self_Employed  \
0    LP001002    Male      No          0      Graduate            No   
1    LP001003    Male     Yes          1      Graduate            No   
2    LP001005    Male     Yes          0      Graduate           Yes   
3    LP001006    Male     Yes          0  Not Graduate            No   
4    LP001008    Male      No          0      Graduate            No   
5    LP001011    Male     Yes          2      Graduate           Yes   
6    LP001013    Male     Yes          0  Not Graduate            No   
7    LP001014    Male     Yes          0      Graduate            No   
8    LP001018    Male     Yes          2      Graduate            No   
9    LP001020    Male     Yes          1      Graduate            No   
10   LP001024    Male     Yes          2      Graduate            No   
11   LP001027    Male     Yes          2      Graduate           NaN   
12   LP001028    Male     Yes          2      Graduate            No   
13   LP001029    Male      No          0      Graduate            No   
14   LP001030    Male     Yes          2      Graduate            No   
15   LP001032    Male      No          0      Graduate            No   
16   LP001034    Male      No          1  Not Graduate            No   
17   LP001036  Female      No          0      Graduate            No   
18   LP001038    Male     Yes          0  Not Graduate            No   
19   LP001041    Male     Yes          0      Graduate           NaN   
20   LP001043    Male     Yes          0  Not Graduate            No   
21   LP001046    Male     Yes          1      Graduate            No   
22   LP001047    Male     Yes          0  Not Graduate            No   
23   LP001050     NaN     Yes          2  Not Graduate            No   
24   LP001052    Male     Yes          1      Graduate           NaN   
25   LP001066    Male     Yes          0      Graduate           Yes   
26   LP001068    Male     Yes          0      Graduate            No   
27   LP001073    Male     Yes          2  Not Graduate            No   
28   LP001086    Male      No          0  Not Graduate            No   
29   LP001087  Female      No          2      Graduate           NaN   
..        ...     ...     ...        ...           ...           ...   
584  LP002911    Male     Yes          1      Graduate            No   
585  LP002912    Male     Yes          1      Graduate            No   
586  LP002916    Male     Yes          0      Graduate            No   
587  LP002917  Female      No          0  Not Graduate            No   
588  LP002925     NaN      No          0      Graduate            No   
589  LP002926    Male     Yes          2      Graduate           Yes   
590  LP002928    Male     Yes          0      Graduate            No   
591  LP002931    Male     Yes          2      Graduate           Yes   
592  LP002933     NaN      No          2      Graduate           Yes   
593  LP002936    Male     Yes          0      Graduate            No   
594  LP002938    Male     Yes          0      Graduate           Yes   
595  LP002940    Male      No          0  Not Graduate            No   
596  LP002941    Male     Yes          2  Not Graduate           Yes   
597  LP002943    Male      No        NaN      Graduate            No   
598  LP002945    Male     Yes          0      Graduate           Yes   
599  LP002948    Male     Yes          2      Graduate            No   
600  LP002949  Female      No          2      Graduate           NaN   
601  LP002950    Male     Yes          0  Not Graduate           NaN   
602  LP002953    Male     Yes          0      Graduate            No   
603  LP002958    Male      No          0      Graduate            No   
604  LP002959  Female     Yes          1      Graduate            No   
605  LP002960    Male     Yes          0  Not Graduate            No   
606  LP002961    Male     Yes          1      Graduate            No   
607  LP002964    Male     Yes          2  Not 

In [13]:
dataset["Gender"].fillna(dataset["Gender"].mode()[0],inplace = True)
dataset["Married"].fillna(dataset["Married"].mode()[0],inplace = True)
dataset["Dependents"].fillna(dataset["Dependents"].mode()[0],inplace = True)
dataset["Self_Employed"].fillna(dataset["Self_Employed"].mode()[0],inplace = True)
dataset["LoanAmount"].fillna(dataset["LoanAmount"].mean(),inplace = True)
dataset["Loan_Amount_Term"].fillna(dataset["Loan_Amount_Term"].mean(),inplace = True)
dataset["Credit_History"].fillna(dataset["Credit_History"].mean(),inplace = True)

In [15]:
dataset.isnull().any()

Loan_ID              False
Gender               False
Married              False
Dependents           False
Education            False
Self_Employed        False
ApplicantIncome      False
CoapplicantIncome    False
LoanAmount           False
Loan_Amount_Term     False
Credit_History       False
Property_Area        False
Loan_Status          False
dtype: bool

In [16]:
dataset["Gender"].mode()[0]

'Male'

In [17]:
dataset["Married"].mode()[0]

'Yes'

In [18]:
dataset["Dependents"].mode()[0]

'0'

In [19]:
dataset["Self_Employed"].mode()[0]

'No'

In [20]:
dataset["LoanAmount"].mode()[0]

146.41216216216216

In [21]:
dataset["Loan_Amount_Term"].mean()

342.0

In [22]:
dataset["Credit_History"].mean()

0.8421985815602844

In [23]:
dataset.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0  146.412162             360.0   
1             4583             1508.0  128.000000             360.0   
2             3000                0.0   66.000000             360.0   
3             2583             2358.0  120.000000             360.0   
4             6000                0.0  141.000000             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

In [24]:
dataset["Gender"].unique()

array(['Male', 'Female'], dtype=object)

In [25]:
dataset["Married"].unique()

array(['No', 'Yes'], dtype=object)

In [26]:
dataset["Education"].unique()

array(['Graduate', 'Not Graduate'], dtype=object)

In [27]:
dataset["Self_Employed"].unique()

array(['No', 'Yes'], dtype=object)

In [28]:
dataset["Property_Area"].unique()

array(['Urban', 'Rural', 'Semiurban'], dtype=object)

In [29]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
dataset["Gender"] = le.fit_transform(dataset["Gender"])
dataset["Married"] = le.fit_transform(dataset["Married"])
dataset["Education"] = le.fit_transform(dataset["Education"])
dataset["Self_Employed"] = le.fit_transform(dataset["Self_Employed"])
dataset["Property_Area"] = le.fit_transform(dataset["Property_Area"])
dataset["Loan_ID"] = le.fit_transform(dataset["Loan_ID"])

In [30]:
dataset.head()

Loan_ID  Gender  Married Dependents  Education  Self_Employed  \
0        0       1        0          0          0              0   
1        1       1        1          1          0              0   
2        2       1        1          0          0              1   
3        3       1        1          0          1              0   
4        4       1        0          0          0              0   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0  146.412162             360.0   
1             4583             1508.0  128.000000             360.0   
2             3000                0.0   66.000000             360.0   
3             2583             2358.0  120.000000             360.0   
4             6000                0.0  141.000000             360.0   

   Credit_History  Property_Area Loan_Status  
0             1.0              2           Y  
1             1.0              0           N  
2             1.0              2           Y  
3             1.0              2           Y  
4             1.0              2           Y

In [31]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
dataset["Loan_Status"] = le.fit_transform(dataset["Loan_Status"])

In [32]:
x = dataset.iloc[:,0:12]
y = dataset.iloc[:,12]

In [33]:
x

Loan_ID  Gender  Married Dependents  Education  Self_Employed  \
0          0       1        0          0          0              0   
1          1       1        1          1          0              0   
2          2       1        1          0          0              1   
3          3       1        1          0          1              0   
4          4       1        0          0          0              0   
5          5       1        1          2          0              1   
6          6       1        1          0          1              0   
7          7       1        1          0          0              0   
8          8       1        1          2          0              0   
9          9       1        1          1          0              0   
10        10       1        1          2          0              0   
11        11       1        1          2          0              0   
12        12       1        1          2          0              0   
13        13       1        0          0          0              0   
14        14       1        1          2          0              0   
15        15       1        0          0          0              0   
16        16       1        0          1          1              0   
17        17       0        0          0          0              0   
18        18       1        1          0          1              0   
19        19       1        1          0          0              0   
20        20       1        1          0          1              0   
21        21       1        1          1          0              0   
22        22       1        1          0          1              0   
23        23       1        1          2          1              0   
24        24       1        1          1          0              0   
25        25       1        1          0          0              1   
26        26       1        1          0          0              0   
27        27       1        1          2          1              0   
28        28       1        0          0          1              0   
29        29       0        0          2          0              0   
..       ...     ...      ...        ...        ...            ...   
584      584       1        1          1          0              0   
585      585       1        1          1          0              0   
586      586       1        1          0          0              0   
587      587       0        0          0          1              0   
588      588       1        0          0          0              0   
589      589       1        1          2          0              1   
590      590       1        1          0          0              0   
591      591       1        1          2          0              1   
592      592       1        0          2          0              1   
593      593       1        1          0          0              0   
594      594       1        1          0          0              1   
595      595       1        0          0          1              0   
596      596       1        1          2          1              1   
597      597       1        0          0          0              0   
598      598       1        1          0          0              1   
599      599       1        1          2          0              0   
600      600       0        0          2          0              0   
601      601       1        1          0          1              0   
602      602       1        1          0          0              0   
603      603       1        0          0          0              0   
604      604       0        1          1          0              0   
605      605       1        1          0          1              0   
606      606       1        1          1          0              0   
607      607       1        1          2          1              0   
608      608       1        1          0          0              0   
609      609   

In [34]:
y

0      1
1      0
2      1
3      1
4      1
5      1
6      1
7      0
8      1
9      0
10     1
11     1
12     1
13     0
14     1
15     1
16     1
17     0
18     0
19     1
20     0
21     1
22     0
23     0
24     0
25     1
26     1
27     1
28     0
29     1
      ..
584    0
585    0
586    1
587    1
588    1
589    0
590    1
591    0
592    1
593    1
594    1
595    1
596    0
597    0
598    1
599    1
600    0
601    1
602    1
603    1
604    1
605    0
606    1
607    1
608    1
609    1
610    1
611    1
612    1
613    0
Name: Loan_Status, Length: 614, dtype: int32

In [35]:
x = dataset.iloc[:,0:12].values
y = dataset.iloc[:,12].values

In [36]:
x

array([[0, 1, 0, ..., 360.0, 1.0, 2],
       [1, 1, 1, ..., 360.0, 1.0, 0],
       [2, 1, 1, ..., 360.0, 1.0, 2],
       ...,
       [611, 1, 1, ..., 360.0, 1.0, 2],
       [612, 1, 1, ..., 360.0, 1.0, 2],
       [613, 0, 0, ..., 360.0, 0.0, 1]], dtype=object)

In [37]:
y

array([1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0,

In [38]:
x.shape

(614, 12)

In [39]:
y.shape

(614,)

In [40]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([("oh", OneHotEncoder(),[1,2,4,5,11])],remainder = "passthrough")
x = ct.fit_transform(x)

C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [41]:
x

array([[0.0, 1.0, 1.0, ..., 146.41216216216216, 360.0, 1.0],
       [0.0, 1.0, 0.0, ..., 128.0, 360.0, 1.0],
       [0.0, 1.0, 0.0, ..., 66.0, 360.0, 1.0],
       ...,
       [0.0, 1.0, 0.0, ..., 253.0, 360.0, 1.0],
       [0.0, 1.0, 0.0, ..., 187.0, 360.0, 1.0],
       [1.0, 0.0, 1.0, ..., 133.0, 360.0, 0.0]], dtype=object)

In [42]:
x.shape

(614, 18)

In [43]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size = 0.2, random_state = 0)

In [44]:
x_train.shape

(491, 18)

In [45]:
x_test.shape

(123, 18)

In [46]:
from sklearn.preprocessing import StandardScaler

In [47]:
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [48]:
x_train

array([[-0.47374983,  0.47374983, -0.71143163, ..., -0.18814516,
         0.27644707,  0.45859914],
       [-0.47374983,  0.47374983,  1.40561644, ...,  0.56269516,
         0.27644707,  0.01148007],
       [-0.47374983,  0.47374983, -0.71143163, ...,  0.01977985,
         0.27644707, -2.37482957],
       ...,
       [-0.47374983,  0.47374983, -0.71143163, ...,  0.60890072,
         0.27644707,  0.45859914],
       [-0.47374983,  0.47374983, -0.71143163, ...,  0.14684514,
         0.27644707,  0.45859914],
       [ 2.11081869, -2.11081869, -0.71143163, ...,  0.40097571,
         0.27644707,  0.45859914]])

In [49]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [50]:
ann = Sequential()

In [51]:
ann.add(Dense(18, kernel_initializer = "random_uniform", activation = "relu"))

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [52]:
ann.add(Dense(36, kernel_initializer = "random_uniform", activation = "relu"))

In [53]:
ann.add(Dense(1, kernel_initializer = "random_uniform", activation = "sigmoid"))

In [54]:
ann.compile("adam","binary_crossentropy",metrics = ["accuracy"])

In [55]:
ann.fit(x_train,y_train,batch_size = 32,epochs = 15)

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Epoch 1/15
491/491 [==============================] - 3s 6ms/sample - loss: 0.6906 - acc: 0.6701
Epoch 2/15
491/491 [==============================] - 0s 855us/sample - loss: 0.6816 - acc: 0.6762
Epoch 3/15
491/491 [==============================] - 0s 650us/sample - loss: 0.6628 - acc: 0.6762
Epoch 4/15
491/491 [==============================] - 0s 701us/sample - loss: 0.6300 - acc: 0.6762
Epoch 5/15
491/491 [==============================] - 0s 587us/sample - loss: 0.5875 - acc: 0.6762
Epoch 6/15
491/491 [==============================] - 0s 401us/sample - loss: 0.5582 - acc: 0.6864
Epoch 7/15
491/491 [==============================] - 0s 523us/sample - loss: 0.5343 - acc: 0.7556
Epoch 8/15
491/491 [==============================] - 0s 391us/sample - loss: 0.5181 - acc: 0.7923
Epoch 9/15
491/491 [==============================] - 0s 497us/sample - loss: 0.5059 - acc: 0.8045
Epoch 10/15
491/4

In [56]:
ypred = ann.predict(x_test)

In [57]:
ypred

array([[0.81383383],
       [0.81020033],
       [0.7370243 ],
       [0.8728031 ],
       [0.89840496],
       [0.12464744],
       [0.87151134],
       [0.64325154],
       [0.09704411],
       [0.9255979 ],
       [0.8546278 ],
       [0.92872703],
       [0.73734957],
       [0.861854  ],
       [0.90302706],
       [0.87569785],
       [0.6413616 ],
       [0.8076719 ],
       [0.5739558 ],
       [0.11135504],
       [0.10755974],
       [0.91991454],
       [0.7665154 ],
       [0.7149632 ],
       [0.64191914],
       [0.8781059 ],
       [0.7011904 ],
       [0.82386124],
       [0.10654518],
       [0.12352523],
       [0.8645879 ],
       [0.5713588 ],
       [0.86438   ],
       [0.7276018 ],
       [0.8678194 ],
       [0.14810625],
       [0.89106494],
       [0.65115494],
       [0.9023814 ],
       [0.88162357],
       [0.7249683 ],
       [0.09932274],
       [0.95985997],
       [0.713573  ],
       [0.82163656],
       [0.541265  ],
       [0.90880406],
       [0.852

In [58]:
ypred = ypred>0.5

In [59]:
ypred

array([[ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [

In [60]:
y_test

array([1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1])

In [61]:
dataset.head(3)

Loan_ID  Gender  Married Dependents  Education  Self_Employed  \
0        0       1        0          0          0              0   
1        1       1        1          1          0              0   
2        2       1        1          0          0              1   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0  146.412162             360.0   
1             4583             1508.0  128.000000             360.0   
2             3000                0.0   66.000000             360.0   

   Credit_History  Property_Area  Loan_Status  
0             1.0              2            1  
1             1.0              0            0  
2             1.0              2            1

In [62]:
yp = ann.predict(sc.transform(ct.transform([[34,1,0,1,1,0,2345,123.6,345,768,1,2]])))

In [63]:
yp

array([[0.23747103]], dtype=float32)

In [64]:
yp>0.5

array([[False]])

# 50strtups - c

In [65]:
dataset = pd.read_csv(r"C:\Users\DELL\Downloads\50_startups.csv")

In [66]:
dataset

R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87              NaN  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08             NaN        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57     Florida  124266.90
19   86419.70       153514.11             0.00    New York  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26     Florida  110352.25
23   67532.53       105751.03        304768.73     Florida  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07     Florida  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28         91131.24     Florida   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81     Florida   96778.92
34   46426.07       157693.92        210797.67  California   96712.80
35   46014.02        85047.44        205517.64    New York   96479.51
36   28663.76       127056.21        201126.82     Florida   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93        185265.10    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67  California   78239.91
41   27892.92        84710.77        164470.71     Florida   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75
47       0.00       135426.92             0.00  California   42559.73
48     542.05        51743.15             0.00    New York   35673.41
49       0.00       116983.80         45173.06  California   14681.40

In [67]:
titles = list(dataset.columns)

In [68]:
titles

['R&D Spend', 'Administration', 'Marketing Spend', 'State', 'Profit']

In [69]:
titles[3],titles[0]= titles[0],titles[3]
titles

['State', 'Administration', 'Marketing Spend', 'R&D Spend', 'Profit']

In [70]:
dataset = dataset[titles]
dataset

State  Administration  Marketing Spend  R&D Spend     Profit
0     New York       136897.80        471784.10  165349.20  192261.83
1   California       151377.59        443898.53  162597.70  191792.06
2      Florida       101145.55        407934.54  153441.51  191050.39
3     New York       118671.85        383199.62  144372.41  182901.99
4      Florida        91391.77        366168.42  142107.34  166187.94
5     New York        99814.71        362861.36  131876.90  156991.12
6   California       147198.87              NaN  134615.46  156122.51
7      Florida       145530.06        323876.68  130298.13  155752.60
8     New York       148718.95        311613.29  120542.52  152211.77
9   California       108679.17        304981.62  123334.88  149759.96
10     Florida             NaN        229160.95  101913.08  146121.95
11  California        91790.61        249744.55  100671.96  144259.40
12     Florida       127320.38        249839.44   93863.75  141585.52
13  California       135495.07        252664.93   91992.39  134307.35
14     Florida       156547.42        256512.92  119943.24  132602.65
15    New York       122616.84        261776.23  114523.61  129917.04
16  California       121597.55        264346.06   78013.11  126992.93
17    New York       145077.58        282574.31   94657.16  125370.37
18     Florida       114175.79        294919.57   91749.16  124266.90
19    New York       153514.11             0.00   86419.70  122776.86
20  California       113867.30        298664.47   76253.86  118474.03
21    New York       153773.43        299737.29   78389.47  111313.02
22     Florida       122782.75        303319.26   73994.56  110352.25
23     Florida       105751.03        304768.73   67532.53  108733.99
24    New York        99281.34        140574.81   77044.01  108552.04
25  California       139553.16        137962.62   64664.71  107404.34
26     Florida       144135.98        134050.07   75328.87  105733.54
27    New York       127864.55        353183.81   72107.60  105008.31
28     Florida       182645.56        118148.20   66051.52  103282.38
29    New York       153032.06        107138.38   65605.48  101004.64
30     Florida       115641.28         91131.24   61994.48   99937.59
31    New York       152701.92         88218.23   61136.38   97483.56
32  California       129219.61         46085.25   63408.86   97427.84
33     Florida       103057.49        214634.81   55493.95   96778.92
34  California       157693.92        210797.67   46426.07   96712.80
35    New York        85047.44        205517.64   46014.02   96479.51
36     Florida       127056.21        201126.82   28663.76   90708.19
37  California        51283.14        197029.42   44069.95   89949.14
38    New York        65947.93        185265.10   20229.59   81229.06
39  California        82982.09        174999.30   38558.51   81005.76
40  California       118546.05        172795.67   28754.33   78239.91
41     Florida        84710.77        164470.71   27892.92   77798.83
42  California        96189.63        148001.11   23640.93   71498.49
43    New York       127382.30         35534.17   15505.73   69758.98
44  California       154806.14         28334.72   22177.74   65200.33
45    New York       124153.04          1903.93    1000.23   64926.08
46     Florida       115816.21        297114.46    1315.46   49490.75
47  California       135426.92             0.00       0.00   42559.73
48    New York        51743.15             0.00     542.05   35673.41
49  California       116983.80         45173.06       0.00   14681.40

In [71]:
dataset.isnull().any()

State              False
Administration      True
Marketing Spend     True
R&D Spend          False
Profit             False
dtype: bool

In [72]:
dataset["Administration"].fillna(dataset["Administration"].mean(),inplace= True)
dataset["Marketing Spend"].fillna(dataset["Marketing Spend"].mean(),inplace= True)


C:\Users\DELL\Anaconda3\lib\site-packages\pandas\core\generic.py:6130: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)


In [73]:
dataset.isnull().any()

State              False
Administration     False
Marketing Spend    False
R&D Spend          False
Profit             False
dtype: bool

In [74]:
dataset

State  Administration  Marketing Spend  R&D Spend     Profit
0     New York   136897.800000    471784.100000  165349.20  192261.83
1   California   151377.590000    443898.530000  162597.70  191792.06
2      Florida   101145.550000    407934.540000  153441.51  191050.39
3     New York   118671.850000    383199.620000  144372.41  182901.99
4      Florida    91391.770000    366168.420000  142107.34  166187.94
5     New York    99814.710000    362861.360000  131876.90  156991.12
6   California   147198.870000    212725.266735  134615.46  156122.51
7      Florida   145530.060000    323876.680000  130298.13  155752.60
8     New York   148718.950000    311613.290000  120542.52  152211.77
9   California   108679.170000    304981.620000  123334.88  149759.96
10     Florida   121564.038163    229160.950000  101913.08  146121.95
11  California    91790.610000    249744.550000  100671.96  144259.40
12     Florida   127320.380000    249839.440000   93863.75  141585.52
13  California   135495.070000    252664.930000   91992.39  134307.35
14     Florida   156547.420000    256512.920000  119943.24  132602.65
15    New York   122616.840000    261776.230000  114523.61  129917.04
16  California   121597.550000    264346.060000   78013.11  126992.93
17    New York   145077.580000    282574.310000   94657.16  125370.37
18     Florida   114175.790000    294919.570000   91749.16  124266.90
19    New York   153514.110000         0.000000   86419.70  122776.86
20  California   113867.300000    298664.470000   76253.86  118474.03
21    New York   153773.430000    299737.290000   78389.47  111313.02
22     Florida   122782.750000    303319.260000   73994.56  110352.25
23     Florida   105751.030000    304768.730000   67532.53  108733.99
24    New York    99281.340000    140574.810000   77044.01  108552.04
25  California   139553.160000    137962.620000   64664.71  107404.34
26     Florida   144135.980000    134050.070000   75328.87  105733.54
27    New York   127864.550000    353183.810000   72107.60  105008.31
28     Florida   182645.560000    118148.200000   66051.52  103282.38
29    New York   153032.060000    107138.380000   65605.48  101004.64
30     Florida   115641.280000     91131.240000   61994.48   99937.59
31    New York   152701.920000     88218.230000   61136.38   97483.56
32  California   129219.610000     46085.250000   63408.86   97427.84
33     Florida   103057.490000    214634.810000   55493.95   96778.92
34  California   157693.920000    210797.670000   46426.07   96712.80
35    New York    85047.440000    205517.640000   46014.02   96479.51
36     Florida   127056.210000    201126.820000   28663.76   90708.19
37  California    51283.140000    197029.420000   44069.95   89949.14
38    New York    65947.930000    185265.100000   20229.59   81229.06
39  California    82982.090000    174999.300000   38558.51   81005.76
40  California   118546.050000    172795.670000   28754.33   78239.91
41     Florida    84710.770000    164470.710000   27892.92   77798.83
42  California    96189.630000    148001.110000   23640.93   71498.49
43    New York   127382.300000     35534.170000   15505.73   69758.98
44  California   154806.140000     28334.720000   22177.74   65200.33
45    New York   124153.040000      1903.930000    1000.23   64926.08
46     Florida   115816.210000    297114.460000    1315.46   49490.75
47  California   135426.920000         0.000000       0.00   42559.73
48    New York    51743.150000         0.000000     542.05   35673.41
49  California   116983.800000     45173.060000       0.00   14681.40

In [75]:
dataset['State'].unique()

array(['New York', 'California', 'Florida'], dtype=object)

In [76]:
x = dataset.iloc[:,1:5].values
y = dataset.iloc[:,0:1].values

In [77]:
y

array([['New York'],
       ['California'],
       ['Florida'],
       ['New York'],
       ['Florida'],
       ['New York'],
       ['California'],
       ['Florida'],
       ['New York'],
       ['California'],
       ['Florida'],
       ['California'],
       ['Florida'],
       ['California'],
       ['Florida'],
       ['New York'],
       ['California'],
       ['New York'],
       ['Florida'],
       ['New York'],
       ['California'],
       ['New York'],
       ['Florida'],
       ['Florida'],
       ['New York'],
       ['California'],
       ['Florida'],
       ['New York'],
       ['Florida'],
       ['New York'],
       ['Florida'],
       ['New York'],
       ['California'],
       ['Florida'],
       ['California'],
       ['New York'],
       ['Florida'],
       ['California'],
       ['New York'],
       ['California'],
       ['California'],
       ['Florida'],
       ['California'],
       ['New York'],
       ['California'],
       ['New York'],
       ['Florida'],

In [78]:
y.ndim

2

In [79]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
one = OneHotEncoder()
z = one.fit_transform(y[:,0:1]).toarray()
y = np.delete(y,0,axis = 1)
y = np.concatenate((z,y),axis = 1)

In [80]:
y

array([[0.0, 0.0, 1.0],
       [1.0, 0.0, 0.0],
       [0.0, 1.0, 0.0],
       [0.0, 0.0, 1.0],
       [0.0, 1.0, 0.0],
       [0.0, 0.0, 1.0],
       [1.0, 0.0, 0.0],
       [0.0, 1.0, 0.0],
       [0.0, 0.0, 1.0],
       [1.0, 0.0, 0.0],
       [0.0, 1.0, 0.0],
       [1.0, 0.0, 0.0],
       [0.0, 1.0, 0.0],
       [1.0, 0.0, 0.0],
       [0.0, 1.0, 0.0],
       [0.0, 0.0, 1.0],
       [1.0, 0.0, 0.0],
       [0.0, 0.0, 1.0],
       [0.0, 1.0, 0.0],
       [0.0, 0.0, 1.0],
       [1.0, 0.0, 0.0],
       [0.0, 0.0, 1.0],
       [0.0, 1.0, 0.0],
       [0.0, 1.0, 0.0],
       [0.0, 0.0, 1.0],
       [1.0, 0.0, 0.0],
       [0.0, 1.0, 0.0],
       [0.0, 0.0, 1.0],
       [0.0, 1.0, 0.0],
       [0.0, 0.0, 1.0],
       [0.0, 1.0, 0.0],
       [0.0, 0.0, 1.0],
       [1.0, 0.0, 0.0],
       [0.0, 1.0, 0.0],
       [1.0, 0.0, 0.0],
       [0.0, 0.0, 1.0],
       [0.0, 1.0, 0.0],
       [1.0, 0.0, 0.0],
       [0.0, 0.0, 1.0],
       [1.0, 0.0, 0.0],
       [1.0, 0.0, 0.0],
       [0.0, 1.0

In [81]:
y.ndim

2

In [82]:
y.shape

(50, 3)

In [83]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 0)

In [84]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)


In [85]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense


In [86]:
cat = Sequential()

In [87]:
cat.add(Dense(3,kernel_initializer = "random_uniform",activation = "relu"))

In [88]:
cat.add(Dense(9,kernel_initializer = "random_uniform",activation = "relu"))

In [89]:
cat.add(Dense(3,kernel_initializer = "random_uniform",activation = "softmax"))

In [90]:
cat.compile("adam","categorical_crossentropy",metrics = ["accuracy"])

In [91]:
cat.fit(x_train,y_train,batch_size=32,epochs = 70)

Epoch 1/70
40/40 [==============================] - 1s 23ms/sample - loss: 1.0986 - acc: 0.3250
Epoch 2/70
40/40 [==============================] - 0s 550us/sample - loss: 1.0983 - acc: 0.4000
Epoch 3/70
40/40 [==============================] - 0s 1ms/sample - loss: 1.0981 - acc: 0.4000
Epoch 4/70
40/40 [==============================] - 0s 450us/sample - loss: 1.0979 - acc: 0.4000
Epoch 5/70
40/40 [==============================] - 0s 500us/sample - loss: 1.0977 - acc: 0.4000
Epoch 6/70
40/40 [==============================] - 0s 600us/sample - loss: 1.0975 - acc: 0.4000
Epoch 7/70
40/40 [==============================] - 0s 425us/sample - loss: 1.0973 - acc: 0.4000
Epoch 8/70
40/40 [==============================] - 0s 600us/sample - loss: 1.0972 - acc: 0.4000
Epoch 9/70
40/40 [==============================] - 0s 850us/sample - loss: 1.0969 - acc: 0.4000
Epoch 10/70
40/40 [==============================] - 0s 675us/sample - loss: 1.0968 - acc: 0.4000
Epoch 11/70
40/40 [=============

In [92]:
x_train.shape

(40, 4)

In [93]:
y_train.shape

(40, 3)

In [94]:
ypred = cat.predict(x_test)

In [95]:
ypred

array([[0.3737145 , 0.27471903, 0.35156643],
       [0.36062443, 0.29325426, 0.3461213 ],
       [0.36027372, 0.29376343, 0.34596288],
       [0.38751814, 0.25557014, 0.35691172],
       [0.36013094, 0.29393578, 0.3459332 ],
       [0.3605384 , 0.29328823, 0.34617332],
       [0.38800514, 0.2548916 , 0.3571033 ],
       [0.3799829 , 0.26596087, 0.35405627],
       [0.36213344, 0.2910585 , 0.34680808],
       [0.3601367 , 0.29392883, 0.3459344 ]], dtype=float32)

In [96]:
ypred[0]

array([0.3737145 , 0.27471903, 0.35156643], dtype=float32)

In [97]:
y_test[0]

array([0.0, 1.0, 0.0], dtype=object)

In [98]:
ypred[1]

array([0.36062443, 0.29325426, 0.3461213 ], dtype=float32)

In [99]:
y_test[1]

array([1.0, 0.0, 0.0], dtype=object)

In [100]:
dataset.head()

State  Administration  Marketing Spend  R&D Spend     Profit
0    New York       136897.80        471784.10  165349.20  192261.83
1  California       151377.59        443898.53  162597.70  191792.06
2     Florida       101145.55        407934.54  153441.51  191050.39
3    New York       118671.85        383199.62  144372.41  182901.99
4     Florida        91391.77        366168.42  142107.34  166187.94

In [101]:
cat.predict_classes(sc.transform([[12345,345,2245,546]]))

array([0], dtype=int64)